### ISSUE TITLE
E5108: Error executing lua /home/tobi/.vim/plugged/deoplete-lsp/lua/hover.lua:10: attempt to in dex field 'handlers' (a nil value)

### ISSUE THREAD

**Issue by wzrdtales** [deoplete-plugins/deoplete-lsp#45]
This error comes after updating to the latest nvim_lsp. Is the compatibility maybe broken currently?

**Comment by jubnzv** [comment]
See: https://github.com/deoplete-plugins/deoplete-lsp/pull/40

I think you also need to update neovim itself.

**Comment by wzrdtales** [comment]
yes you're right... the maintainer of the neovim-git aur repo is not actually maintaining it as expected. now that i manually updated it it works. thanks for the quick response
