### ISSUE TITLE
attempt to index field 'handlers' (a nil value)

### ISSUE THREAD

**Issue by giddie** [deoplete-plugins/deoplete-lsp#49]
nvim v0.7.0
deoplete-lsp c466c955e85d995984a8135e16da71463712e5e5

I sometimes get the following error on completion. I'm not sure quite where to start looking for the cause. I'm using `elixirls` and `null-ls`. Is it likely to be an issue caused by one of these sources? I'd be grateful for a pointer in the general direction of a cause, and I'll do my best to dig further.

```
Error executing vim.schedule lua callback: .../.vim-config/vim-dir/vim-plug/deoplete-lsp/lua/hover.lua:78: attempt to index field 'handlers' (a nil value)
stack traceback:
        .../.vim-config/vim-dir/vim-plug/deoplete-lsp/lua/hover.lua:78: in function 'set_response_handler'
        .../.vim-config/vim-dir/vim-plug/deoplete-lsp/lua/hover.lua:134: in function 'request_hover'
        .../.vim-config/vim-dir/vim-plug/deoplete-lsp/lua/hover.lua:144: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by Shougo** [comment]
Please use the latest.

**Comment by giddie** [comment]
Awesome; thanks for the quick fix :heart:
