### ISSUE TITLE
`client_with_hover` function should use `client.server_capabilities`, as `client.resolved_capabilities` has been deprecated in Neovim 0.8

### ISSUE THREAD

**Issue by zyrif** [deoplete-plugins/deoplete-lsp#55]
# Problems summary
In [hover.lua](https://github.com/deoplete-plugins/deoplete-lsp/blob/09a476e0301c7253e7cf459cea605878c51c370d/lua/hover.lua#L96), deoplete-lsp consults `client.resolved_capabilities` to check if the server supports hover, however this has been [deprecated in Neovim 0.8](https://github.com/neovim/neovim/pull/17814)

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/24279322/206957348-4350cf90-25a6-4b4e-af1b-b1b2a49becd3.png)

**Comment by Shougo** [comment]
Please test #56.

**Comment by zyrif** [comment]
Thanks for the quick response!

`server_capabilities` is a lua table, so calling it errors out. Removing the parentheses should fix the error.

![image](https://user-images.githubusercontent.com/24279322/206993462-ce2d9729-4013-4841-be0f-fdb1f537464c.png)

**Comment by Shougo** [comment]
Thanks.  Fixed the problem.  Please test the latest.

**Comment by zyrif** [comment]
Confirming that the issue has been resolved. Thank you very much!
